version: "3"
services:
  app:
    container_name: big-bear-mealie
    image: hkotel/mealie:v3.3.2
    restart: unless-stopped
    volumes:
      - mealie_data:/app/data
    ports:
      - "9925:9000"
volumes:
  mealie_data:
